title: Portal Geoespacial del Proyecto Cosecha de Agua
description: Portal Geoespacial del Proyecto Cosecha de Agua

baseurl: /geo-cosecha-agua.github.io
color-scheme: "mediumseagreen" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
